export const apenasLestras = [
  { id: 11, letra: "A", status: "padrao", alt: ["A", "Á", "À", "Ã", "Â", "Ä"] },
  { id: 12, letra: "B", status: "padrao", alt: ["B"] },
  { id: 13, letra: "C", status: "padrao", alt: ["C", "Ç"] },
  { id: 14, letra: "D", status: "padrao", alt: ["D"] },
  { id: 15, letra: "E", status: "padrao", alt: ["E", "É", "È", "Ê", "Ë"] },
  { id: 16, letra: "F", status: "padrao", alt: ["F"] },
  { id: 17, letra: "G", status: "padrao", alt: ["G"] },
  { id: 18, letra: "H", status: "padrao", alt: ["H"] },
  { id: 19, letra: "I", status: "padrao", alt: ["I", "Í", "Ì", "Î", "Ï"] },
  { id: 20, letra: "J", status: "padrao", alt: ["J"] },
  { id: 21, letra: "K", status: "padrao", alt: ["K"] },
  { id: 22, letra: "L", status: "padrao", alt: ["L"] },
  { id: 23, letra: "M", status: "padrao", alt: ["M"] },
  { id: 24, letra: "N", status: "padrao", alt: ["N"] },
  { id: 25, letra: "O", status: "padrao", alt: ["O", "Ó", "Ò", "Õ", "Ô", "Ö"] },
  { id: 26, letra: "P", status: "padrao", alt: ["P"] },
  { id: 27, letra: "Q", status: "padrao", alt: ["Q"] },
  { id: 28, letra: "R", status: "padrao", alt: ["R"] },
  { id: 29, letra: "S", status: "padrao", alt: ["S"] },
  { id: 30, letra: "T", status: "padrao", alt: ["T"] },
  { id: 31, letra: "U", status: "padrao", alt: ["U", "Ú", "Ù", "Û", "Ü"] },
  { id: 32, letra: "V", status: "padrao", alt: ["V"] },
  { id: 33, letra: "W", status: "padrao", alt: ["W"] },
  { id: 34, letra: "X", status: "padrao", alt: ["X"] },
  { id: 35, letra: "Y", status: "padrao", alt: ["Y"] },
  { id: 36, letra: "Z", status: "padrao", alt: ["Z"] },
];
export const lestrasEnumeros = [
  { id: 1, letra: "1", status: "padrao", alt: ["1"] },
  { id: 2, letra: "2", status: "padrao", alt: ["2"] },
  { id: 3, letra: "3", status: "padrao", alt: ["3"] },
  { id: 4, letra: "4", status: "padrao", alt: ["4"] },
  { id: 5, letra: "5", status: "padrao", alt: ["5"] },
  { id: 6, letra: "6", status: "padrao", alt: ["6"] },
  { id: 7, letra: "7", status: "padrao", alt: ["7"] },
  { id: 8, letra: "8", status: "padrao", alt: ["8"] },
  { id: 9, letra: "9", status: "padrao", alt: ["9"] },
  { id: 10, letra: "0", status: "padrao", alt: ["0"] },
  { id: 37, letra: " ", status: "padrao", alt: [" "] },
  { id: 11, letra: "A", status: "padrao", alt: ["A", "Á", "À", "Ã", "Â", "Ä"] },
  { id: 12, letra: "B", status: "padrao", alt: ["B"] },
  { id: 13, letra: "C", status: "padrao", alt: ["C", "Ç"] },
  { id: 14, letra: "D", status: "padrao", alt: ["D"] },
  { id: 15, letra: "E", status: "padrao", alt: ["E", "É", "È", "Ê", "Ë"] },
  { id: 16, letra: "F", status: "padrao", alt: ["F"] },
  { id: 17, letra: "G", status: "padrao", alt: ["G"] },
  { id: 18, letra: "H", status: "padrao", alt: ["H"] },
  { id: 19, letra: "I", status: "padrao", alt: ["I", "Í", "Ì", "Î", "Ï"] },
  { id: 20, letra: "J", status: "padrao", alt: ["J"] },
  { id: 21, letra: "K", status: "padrao", alt: ["K"] },
  { id: 22, letra: "L", status: "padrao", alt: ["L"] },
  { id: 23, letra: "M", status: "padrao", alt: ["M"] },
  { id: 24, letra: "N", status: "padrao", alt: ["N"] },
  { id: 25, letra: "O", status: "padrao", alt: ["O", "Ó", "Ò", "Õ", "Ô", "Ö"] },
  { id: 26, letra: "P", status: "padrao", alt: ["P"] },
  { id: 27, letra: "Q", status: "padrao", alt: ["Q"] },
  { id: 28, letra: "R", status: "padrao", alt: ["R"] },
  { id: 29, letra: "S", status: "padrao", alt: ["S"] },
  { id: 30, letra: "T", status: "padrao", alt: ["T"] },
  { id: 31, letra: "U", status: "padrao", alt: ["U", "Ú", "Ù", "Û", "Ü"] },
  { id: 32, letra: "V", status: "padrao", alt: ["V"] },
  { id: 33, letra: "W", status: "padrao", alt: ["W"] },
  { id: 34, letra: "X", status: "padrao", alt: ["X"] },
  { id: 35, letra: "Y", status: "padrao", alt: ["Y"] },
  { id: 36, letra: "Z", status: "padrao", alt: ["Z"] },
];
